# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---
include:
  # Left side firmware
  - board: nice_nano_v2
    shield: sofle_choc_v2_left
    keymap: my_keymap
    artifact-name: sofle_choc_v2_left_firmware
  
  # Right side firmware
  - board: nice_nano_v2
    shield: sofle_choc_v2_right
    keymap: my_keymap
    artifact-name: sofle_choc_v2_right_firmware
  
  # Left side reset firmware
  - board: nice_nano_v2
    shield: sofle_choc_v2_left
    keymap: my_keymap
    config: reset.conf
    artifact-name: sofle_choc_v2_left_reset_firmware
    
  # Right side reset firmware
  - board: nice_nano_v2
    shield: sofle_choc_v2_right
    keymap: my_keymap
    config: reset.conf
    artifact-name: sofle_choc_v2_right_reset_firmware